2014/11/09 01:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "indexhtml".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('indexhtml')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('indexhtml')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/indexhtml')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/site/indexhtml
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/pagehtml?view=about
---
2014/11/09 01:24:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "indexhtml".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('indexhtml')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('indexhtml')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/indexhtml')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/site/indexhtml
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/pagehtml?view=about
---
2014/11/09 01:24:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "indexhtml".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('indexhtml')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('indexhtml')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/indexhtml')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/site/indexhtml
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/pagehtml?view=about
---
2014/11/09 01:24:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "indexhtml".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('indexhtml')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('indexhtml')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/indexhtml')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/site/indexhtml
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/pagehtml?view=about
---
2014/11/09 01:35:24 [error] [php] include(Pais.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php(25): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php(18): ConvocatoriaController->renderPartial()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(782): ConvocatoriaController->renderPartial()
#9 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(79): ConvocatoriaController->render()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ConvocatoriaController->runAction()
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ConvocatoriaController->filterAccessControl()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): ConvocatoriaController->runActionWithFilters()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ConvocatoriaController->run()
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php (25)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php (18)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (79)
2014/11/09 01:35:26 [error] [php] include(Pais.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php(25): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php(18): ConvocatoriaController->renderPartial()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(782): ConvocatoriaController->renderPartial()
#9 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(79): ConvocatoriaController->render()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ConvocatoriaController->runAction()
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ConvocatoriaController->filterAccessControl()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): ConvocatoriaController->runActionWithFilters()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ConvocatoriaController->run()
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php (25)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php (18)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (79)
2014/11/09 01:35:28 [error] [php] include(Pais.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php(25): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php(18): ConvocatoriaController->renderPartial()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(782): ConvocatoriaController->renderPartial()
#9 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(79): ConvocatoriaController->render()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ConvocatoriaController->runAction()
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ConvocatoriaController->filterAccessControl()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): ConvocatoriaController->runActionWithFilters()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ConvocatoriaController->run()
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php (25)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php (18)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (79)
2014/11/09 01:35:58 [error] [php] include(Pais.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php(25): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#4 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php(18): ConvocatoriaController->renderPartial()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ConvocatoriaController->renderInternal()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(869): ConvocatoriaController->renderFile()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(782): ConvocatoriaController->renderPartial()
#9 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(79): ConvocatoriaController->render()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ConvocatoriaController->runAction()
#13 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ConvocatoriaController->filterAccessControl()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): ConvocatoriaController->runActionWithFilters()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ConvocatoriaController->run()
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\_form.php (25)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\views\convocatoria\create.php (18)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (79)
2014/11/09 01:43:07 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:43:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:43:59 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:43:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:47:46 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:47:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:53:28 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:53:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:54:44 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:54:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:54:48 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:54:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 01:56:06 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32).
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php (73)
in C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php (13)
2014/11/09 01:56:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'fecha_resultado_preliminar' at row 1. The SQL statement executed was: INSERT INTO `convocatoria` (`tipo_convocatoria`, `subtipo_convocatoria`, `convocatoria_programa`, `tipo_financiacion`, `fecha_apertura`, `fecha_cierre`, `fecha_resultado_preliminar`, `fecha_resultado_definitivo`, `convocatoria`, `codigo_convocatoria`, `descripcion`, `objeto`, `dirigido_a`, `programa_base`, `instituciones_financiadoras`, `maximo_porcentaje_financiar`, `minimo_porcentaje_financiar`, `minimo_porcentaje_contrapartida_dinero`, `minimo_porcentaje_contrapartida_especie`, `monto_maximo_financiar`, `numero_maximo_meses_proyecto`, `monto_total_convocatoria`, `convenio`, `cdp`, `fecha_cdp`, `cdr`, `fecha_cdr`, `url`, `linea_investigacion`, `postulacion_anticipada`, `definir_estructura_convocatoria`, `numero_proyecto_inversion`, `vigencia`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28, :yp29, :yp30, :yp31, :yp32)' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/convocatoria/create.html
---
2014/11/09 02:06:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('create')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/create.html
---
2014/11/09 02:06:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('create')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/create
---
2014/11/09 02:07:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Convocatoria))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(65): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/login.html
---
2014/11/09 02:08:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Convocatoria))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(65): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
HTTP_REFERER=http://localhost/yii/moduloConvocatoriaSII/site/login.html
---
2014/11/09 02:08:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Convocatoria))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\yii\moduloConvocatoriaSII\protected\controllers\ConvocatoriaController.php(65): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ConvocatoriaController->actionCreate()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('convocatoria/cr...')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii\moduloConvocatoriaSII\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/moduloConvocatoriaSII/convocatoria/create.html
---
